### PR TITLE
Update issue templates to enforce consistency 

### PR DESCRIPTION
**Pull request by boehs**

### CODE REVIEW

**Comment by auguwu** [comment]
Can you push this to the `edge` branch? I don't like contributors + developers pushing to the master branch due to conflicts with the `edge` branch, CI/CD, and it's on production.

**Comment by boehs** [comment]
I don't understand this conflict 🤔

**Comment by auguwu** [comment]
can you redo this PR again, I kinda messed up 😅

**Comment by boehs** [comment]
Or, not? It seems you handled it in #8bea769

**Comment by auguwu** [comment]
yea don't, I did it on my own

**Pull request closed without merging**
